In [65]:
import numpy as np
import pandas as pd

In [66]:
data=pd.DataFrame([
    [np.nan,18,22],
    [np.nan,np.nan,22],
    [18,18,22],
    [np.nan,np.nan,np.nan],
] ,columns=[1,2,3])
data


1     2     3
0   NaN  18.0  22.0
1   NaN   NaN  22.0
2  18.0  18.0  22.0
3   NaN   NaN   NaN

In [67]:
pd.isnull(data).sum()

1    3
2    2
3    1
dtype: int64

In [68]:
pd.isna(data)

1      2      3
0   True  False  False
1   True   True  False
2  False  False  False
3   True   True   True

In [69]:
pd.notna(data)

1      2      3
0  False   True   True
1  False  False   True
2   True   True   True
3  False  False  False

In [70]:
data.fillna(15)

1     2     3
0  15.0  18.0  22.0
1  15.0  15.0  22.0
2  18.0  18.0  22.0
3  15.0  15.0  15.0

In [71]:
data.fillna(data.mean())

1     2     3
0  18.0  18.0  22.0
1  18.0  18.0  22.0
2  18.0  18.0  22.0
3  18.0  18.0  22.0

In [72]:
data.fillna(data.mean()[3])

1     2     3
0  22.0  18.0  22.0
1  22.0  22.0  22.0
2  18.0  18.0  22.0
3  22.0  22.0  22.0

In [73]:
data.fillna(method='ffill')

1     2     3
0   NaN  18.0  22.0
1   NaN  18.0  22.0
2  18.0  18.0  22.0
3  18.0  18.0  22.0

In [74]:
data.fillna(value={1:13},limit=2)

1     2     3
0  13.0  18.0  22.0
1  13.0   NaN  22.0
2  18.0  18.0  22.0
3   NaN   NaN   NaN

In [75]:
data.dropna()

1     2     3
2  18.0  18.0  22.0

In [76]:
data.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [77]:
data[2].dropna()

0    18.0
2    18.0
Name: 2, dtype: float64

In [78]:
data.dropna(thresh=2)

1     2     3
0   NaN  18.0  22.0
2  18.0  18.0  22.0

In [79]:
data.dropna(how="all")

1     2     3
0   NaN  18.0  22.0
1   NaN   NaN  22.0
2  18.0  18.0  22.0

In [80]:
from sklearn.preprocessing import MinMaxScaler

In [81]:
data2=pd.DataFrame([
    [18,1000000],
    [40,5000000],
    [25,3500000]
    ],columns=['age','salary']                  
)
data2

age   salary
0   18  1000000
1   40  5000000
2   25  3500000

In [82]:
scaler=MinMaxScaler()
scaler.fit(data2)
scaler.transform(data2)

array([[0.        , 0.        ],
       [1.        , 1.        ],
       [0.31818182, 0.625     ]])

In [83]:
from sklearn.preprocessing import normalize

In [84]:
normalized_data1=normalize(data2,norm='l1' , axis=0)
normalized_data1


array([[0.21686747, 0.10526316],
       [0.48192771, 0.52631579],
       [0.30120482, 0.36842105]])

In [85]:
normalized_data2=normalize(data2,norm='l2' , axis=0)
normalized_data2

array([[0.35652303, 0.16169042],
       [0.7922734 , 0.80845208],
       [0.49517087, 0.56591646]])